---
apiVersion: batch/v1
kind: Job
metadata:
  name: myprogram
spec:
  backoffLimit: 3
  template:
    metadata:
      name: myprogram-pod
    spec:
      containers:
      - args:
        - -u
        - https://news.ycombinator.com/
        - -u
        - https://arstechnica.com/
        - -o
        - json
        image: myprogram/myprogram
        imagePullPolicy: Never
        name: myprogram
        resources:
          limits:
            cpu: "3"
            memory: 128Mi
      restartPolicy: Never
      securityContext:
        fsGroup: 3000
        runAsGroup: 2000
        runAsUser: 1000
